### ISSUE TITLE
kpr  cpu占用异常

### ISSUE THREAD

**Issue by tcsr200722** [firker/diy-ziyong#14]
几乎是每过24小时，kpr所占cpu就会直接飙到98-100%，导致系统死机。

**Comment by firker** [comment]
ssh执行:
wget -4 -O /usr/share/koolproxy/kpupdate https://raw.githubusercontent.com/firkerword/KPR/main/kpupdate1 && chmod 775 /usr/share/koolproxy/kpupdate
再次更新规则

**Comment by tcsr200722** [comment]
已正常运行1天

**Comment by tcsr200722** [comment]
问题仍然存在    cpu就会直接飙到98-100%，导致系统死机。

**Comment by firker** [comment]
信息不足无法复现该问题  请尝试DD指令重新刷机
